apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    class: btech
spec:
  replicas: 2
  selector:
    matchLabels:
      class: btech
  template:
    metadata:
      name: p1
      labels:
        class: btech
    spec:
      containers:
      - name: cont
        image: python:3.11.15-trixie
        command: ["/bin/sh","-c"]
        args:
        - "sleep infinity"  
          

