apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: c1
    image: httpd:latest
  - name: pythoncont
    image: python:3.11.15-trixie
    command: ["/bin/sh","-c"]
    args:
    - "sleep infinity"
