apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
  labels:
    nm: dp
spec:
  replicas: 2
  selector:
     matchLabels:
        nm: dp
  template:
    metadata:
      name: sql1
      labels:
        nm: dp
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_ROOT_PASSWORD

    
    

